# Generated by Django 5.1 on 2024-09-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('nascimento', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
    ]
